/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GekkoRouteImport } from './routes/gekko'
import { Route as PumpRouteImport } from './routes/pump'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GekkoRoute = GekkoRouteImport.update({
  id: '/gekko',
  path: '/gekko',
  getParentRoute: () => rootRouteImport,
} as any)
const PumpRoute = PumpRouteImport.update({
  id: '/pump',
  path: '/pump',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gekko': typeof GekkoRoute
  '/pump': typeof PumpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gekko': typeof GekkoRoute
  '/pump': typeof PumpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gekko': typeof GekkoRoute
  '/pump': typeof PumpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gekko' | '/pump'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gekko' | '/pump'
  id: '__root__' | '/' | '/gekko' | '/pump'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GekkoRoute: typeof GekkoRoute
  PumpRoute: typeof PumpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gekko': {
      id: '/gekko'
      path: '/gekko'
      fullPath: '/gekko'
      preLoaderRoute: typeof GekkoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pump': {
      id: '/pump'
      path: '/pump'
      fullPath: '/pump'
      preLoaderRoute: typeof PumpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GekkoRoute: GekkoRoute,
  PumpRoute: PumpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
